### ISSUE TITLE
Make this a CLI package

### ISSUE THREAD

**Issue by fregante** [valorkin/eslint-rules-mapper#1]
Are you interested in making this package user-friendly and pushing it as a jshint-switcher tool?

I could work [meow](https://github.com/sindresorhus/meow) into it to use it like:

``` sh
    eslint-rules-mapper .jshintrc
    #or
    eslint-rules-mapper /path/to/paradise/
    #or
    eslint-rules-mapper
```

And it will automatically read the current .jshintrc file and spit out an .eslintrc file

**Comment by ismyrnow** [comment]
My PR makes some progress toward this. It's not using meow, but parsing the argument manually (simple enough to do in this case). It also doesn't work with paths, or default to the current directory.

If those were added, then it would just be a matter of publishing this to npm, I assume? I'm not sure what else goes into installable cli packages.

**Comment by valorkin** [comment]
@ismyrnow looks good to me!
