### ISSUE TITLE
Add max-* and complexity

### ISSUE THREAD

**Issue by jmrnilsson** [valorkin/eslint-rules-mapper#16]
Current version doesn't support (perhaps it's possible to add):
-   "max-depth": [1, 6],
-    "max-params": [2, 6],
-   "complexity": [1, 6],
-   "max-len": [2, 100, 4, {"ignoreUrls": true}],
-  'global-strict' converts but has been replaced with 'strict' in latest eslint version 

**Version**

```
$ npm --version eslint-rules-mapper 
3.6.0
```

**.jshintrc**

```
"maxlen": 100,
```

**.eslintrc**

```
"max-len": [2, 100, 4, {"ignoreUrls": true}],
```
- http://eslint.org/docs/rules/max-len

Great job on this :+1:

**Comment by valorkin** [comment]
This project is not actively maintained, so if you can add PR 
It will be merged and published

**Comment by jmrnilsson** [comment]
sure, I might be able to take a look soon

**Comment by valorkin** [comment]
awesome, thank you
