### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by raphaelokon** [valorkin/eslint-rules-mapper#4]
Is this project still in development? I have plenty of JSHint based projects I would like to migrate to ESLint – without dealing with one-to-one mapping work. The current script throws an `error`.

**Comment by valorkin** [comment]
@interactionist this week I will have some time for it

**Comment by raphaelokon** [comment]
Brill. I could do a quick UI for it; and it could be exposed like a small _drag and drop_ online converter for jshint => es lint

**Comment by pdehaan** [comment]
We recently fixed a few issues, but more PRs are always welcome.
I still need to test how this works with the new **eslint@1** which was released the other day.

**Comment by valorkin** [comment]
@pdehaan initially I was planning this as jscs, jshint to eslint rules mapper
but I have already moved all my projects to eslint and this one became low priority for me :(
