### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by avdg** [valorkin/eslint-rules-mapper#5]
Hey, I'm just looking for options on how I can use this code as I have to maintain eslintrc as rclintrc files. I could copy the code, but its way easier to maintain for everybody I guess if the code is simply on npm though I would understand that setting it up and maintaining it can be a bit too much.

**Comment by avdg** [comment]
Hmm... I guess I'll just copy the library folder for now

**Comment by tilmanschweitzer** [comment]
`npm install -g eslint-rules-mapper` does not work.

Therefore +1

**Comment by valorkin** [comment]
good idea

**Comment by valorkin** [comment]
published https://www.npmjs.com/package/eslint-rules-mapper
any one what to update mappings? :)
